import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const desktopRoot = resolve(import.meta.dirname, '..')

describe('desktop preload packaging', () => {
  it('emits CommonJS preload faces for sandboxed Electron windows', () => {
    const config = readFileSync(resolve(desktopRoot, 'tsdown.config.ts'), 'utf8')
    const main = readFileSync(resolve(desktopRoot, 'src/main.ts'), 'utf8')
    const mainPreload = readFileSync(resolve(desktopRoot, 'src/main-window-preload.ts'), 'utf8')
    const backgroundLifecycle = readFileSync(resolve(desktopRoot, 'src/window-background-lifecycle.ts'), 'utf8')

    expect(config).toContain("format: ['esm', 'cjs']")
    expect(main).toContain("new URL('./main-window-preload.cjs', import.meta.url)")
    expect(main).not.toContain('artifact-renderer-preload')
    expect(main).not.toContain("new URL('./main-window-preload.js', import.meta.url)")
    expect(mainPreload).toContain('import type { DesktopUpdateProgress, DesktopUpdateSnapshot }')
    expect(mainPreload).not.toContain('import {\n  UPDATE_CHECK_CHANNEL')
    expect(mainPreload).toContain("const UPDATE_CHECK_CHANNEL = 'gongchuang:update:check'")
    expect(mainPreload).toContain("const AVATAR_READ_CHANNEL = 'gongchuang:profile-avatar:read'")
    expect(mainPreload).toContain("const AVATAR_WRITE_CHANNEL = 'gongchuang:profile-avatar:write'")
    expect(mainPreload).toContain("const DOCUMENT_IMPORT_CHANNEL = 'gongchuang:documents:import'")
    expect(mainPreload).toContain("const DOCUMENT_DROP_IMPORT_CHANNEL = 'gongchuang:documents:import-dropped'")
    expect(mainPreload).toContain("const DOCUMENT_OPEN_CHANNEL = 'gongchuang:documents:open-imported'")
    expect(mainPreload).toContain("const SESSION_ATTACHMENT_OPEN_CHANNEL = 'gongchuang:documents:open-session-attachment'")
    expect(mainPreload).toContain('openSessionAttachment:')
    expect(mainPreload).toContain("const DESKTOP_PREFERENCES_READ_CHANNEL = 'gongchuang:desktop-preferences:read'")
    expect(mainPreload).toContain("const DESKTOP_CLOSE_BEHAVIOR_WRITE_CHANNEL = 'gongchuang:desktop-preferences:close-behavior'")
    expect(mainPreload).toContain("const DESKTOP_CLOSE_REQUEST_CHANNEL = 'gongchuang:desktop-close:request'")
    expect(mainPreload).toContain("const DESKTOP_CLOSE_RESPONSE_CHANNEL = 'gongchuang:desktop-close:response'")
    expect(mainPreload).toContain('webUtils.getPathForFile(file)')
    expect(mainPreload).toContain("const WORKSPACE_ROOT_STATE_CHANNEL = 'gongchuang:workspace-root:state'")
    expect(mainPreload).toContain("const WORKSPACE_ROOT_CHOOSE_CHANNEL = 'gongchuang:workspace-root:choose'")
    expect(mainPreload).toContain("const WORKSPACE_ROOT_USE_DEFAULT_CHANNEL = 'gongchuang:workspace-root:use-default'")
    expect(mainPreload).toContain("const ENTERPRISE_WORKSPACE_CREATE_CHANNEL = 'gongchuang:enterprise-workspace:create'")
    expect(mainPreload).toContain("const ENTERPRISE_WORKSPACE_IMPORT_CHANNEL = 'gongchuang:enterprise-workspace:import'")
    expect(mainPreload).toContain("const ENTERPRISE_WORKSPACE_TRASH_CHANNEL = 'gongchuang:enterprise-workspace:trash'")
    expect(mainPreload).toContain("const ENTERPRISE_CONVERSATION_TRASH_CHANNEL = 'gongchuang:enterprise-conversation:trash'")
    expect(mainPreload).toContain('importDocuments: (workspacePath: string)')
    expect(mainPreload).toContain('readWindowsCloseBehavior: ()')
    expect(mainPreload).toContain('writeWindowsCloseBehavior: (value: WindowsCloseBehavior)')
    expect(mainPreload).toContain('onWindowsCloseRequested: (listener: (requestId: string) => void)')
    expect(mainPreload).toContain('respondWindowsCloseRequest: (')
    expect(mainPreload).toContain('openImportedDocument: (workspacePath: string, relativePath: string)')
    expect(mainPreload).toContain('createEnterpriseWorkspace: name =>')
    expect(mainPreload).toContain('trashEnterpriseWorkspace: (workspaceId: string)')
    expect(mainPreload).toContain('trashEnterpriseConversation: (sessionId: string)')
    expect(main).toContain('registerWorkspaceRootIpc({')
    expect(main).toContain("extensions: ['*']")
    expect(main).toContain('defaultPath')
    expect(main).toContain("app.commandLine.appendSwitch('lang', PRODUCT_LOCALE)")
    const manifest = JSON.parse(readFileSync(resolve(desktopRoot, 'package.json'), 'utf8')) as {
      build: { win: { electronLanguages: string[] } }
    }
    expect(manifest.build.win.electronLanguages).toEqual(['zh-CN', 'en-US'])
    expect(main).toContain('process.env.GONGCHUANG_SKILL_PLUGIN_ROOT = skillBundle')
    expect(main).toContain("process.on('SIGTERM', () => { beginDesktopHostShutdown(0) })")
    expect(main).toContain("process.on('SIGINT', () => { beginDesktopHostShutdown(130) })")
    expect(main).toContain('forceDesktopProcessExit(exitCode)')
    expect(main).toContain("window.on('close', (event) => {")
    expect(main).toContain('closeWindowToBackground(event, window, quitting)')
    expect(main).toContain("process.platform === 'win32' && windowsCloseBehavior === 'quit'")
    expect(main).toContain('await configureDesktopPreferences()')
    expect(main).not.toContain('window.minimize()')
    expect(backgroundLifecycle).toContain('event.preventDefault()')
    expect(backgroundLifecycle).toContain('window.hide()')
    expect(main).toContain("app.on('activate', () => {")
    expect(main).toContain('desktop runtime shutdown complete pid=')
  })
})
